version: 0.0.9
name: eth_sig_util_plus
description: "Ethereum signature utility porting from JS, plus maintained by org."
repository: https://github.com/dart-anchor/eth_sig_util_plus

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  pointycastle: ">=3.0.1 <5.0.0"
  equatable: ^2.0.3
  collection: ^1.14.11
  buffer: ^1.0.6
  convert: ^3.0.0

dev_dependencies:
  test: ^1.17.10
